
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package edu.cmu.ml.rtw.generic.parse;

/** CUP generated interface containing symbol constants. */
public interface CtxSymbol {
  /* terminals */
  public static final int LSQUARE_BRACKET = 10;
  public static final int RSQUARE_BRACKET = 11;
  public static final int DOLLAR = 5;
  public static final int SEMI = 4;
  public static final int COMP = 7;
  public static final int STRING = 14;
  public static final int EOF = 0;
  public static final int RIGHT_ARROW = 6;
  public static final int LCURLY_BRACE = 12;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RPAREN = 9;
  public static final int RCURLY_BRACE = 13;
  public static final int EQUALS = 3;
  public static final int LPAREN = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "EQUALS",
  "SEMI",
  "DOLLAR",
  "RIGHT_ARROW",
  "COMP",
  "LPAREN",
  "RPAREN",
  "LSQUARE_BRACKET",
  "RSQUARE_BRACKET",
  "LCURLY_BRACE",
  "RCURLY_BRACE",
  "STRING"
  };
}

